/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdvisoryId = IDL.Nat;
export const SchemeId = IDL.Nat;
export const PriceId = IDL.Nat;
export const SoilReportId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FarmerId = IDL.Nat;
export const FarmerProfile = IDL.Record({
  'id' : FarmerId,
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'landSize' : IDL.Float64,
  'location' : IDL.Text,
});
export const CropAdvisory = IDL.Record({
  'id' : AdvisoryId,
  'crop' : IDL.Text,
  'season' : IDL.Text,
  'guidance' : IDL.Text,
});
export const QueryId = IDL.Nat;
export const ExpertQuery = IDL.Record({
  'id' : QueryId,
  'farmerId' : FarmerId,
  'question' : IDL.Text,
  'owner' : IDL.Principal,
  'response' : IDL.Opt(IDL.Text),
  'attachment' : IDL.Opt(IDL.Text),
});
export const GovernmentScheme = IDL.Record({
  'id' : SchemeId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
});
export const MandiPrice = IDL.Record({
  'id' : PriceId,
  'crop' : IDL.Text,
  'price' : IDL.Int,
  'location' : IDL.Text,
});
export const SoilReport = IDL.Record({
  'id' : SoilReportId,
  'ph' : IDL.Float64,
  'farmerId' : FarmerId,
  'owner' : IDL.Principal,
  'recommendations' : IDL.Text,
  'nutrients' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'landSize' : IDL.Float64,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCropAdvisory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AdvisoryId],
      [],
    ),
  'addGovernmentScheme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SchemeId],
      [],
    ),
  'addMandiPrice' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [PriceId], []),
  'addSoilReport' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [SoilReportId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCropAdvisory' : IDL.Func([AdvisoryId], [], []),
  'deleteGovernmentScheme' : IDL.Func([SchemeId], [], []),
  'deleteMandiPrice' : IDL.Func([PriceId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropAdvisories' : IDL.Func([], [IDL.Vec(CropAdvisory)], ['query']),
  'getCropAdvisory' : IDL.Func(
      [AdvisoryId],
      [IDL.Opt(CropAdvisory)],
      ['query'],
    ),
  'getExpertQueries' : IDL.Func([], [IDL.Vec(ExpertQuery)], ['query']),
  'getExpertQuery' : IDL.Func([QueryId], [IDL.Opt(ExpertQuery)], ['query']),
  'getGovernmentScheme' : IDL.Func(
      [SchemeId],
      [IDL.Opt(GovernmentScheme)],
      ['query'],
    ),
  'getGovernmentSchemes' : IDL.Func([], [IDL.Vec(GovernmentScheme)], ['query']),
  'getMandiPrice' : IDL.Func([PriceId], [IDL.Opt(MandiPrice)], ['query']),
  'getMandiPrices' : IDL.Func([], [IDL.Vec(MandiPrice)], ['query']),
  'getMigrationResult' : IDL.Func([], [IDL.Bool], ['query']),
  'getSoilReport' : IDL.Func([SoilReportId], [IDL.Opt(SoilReport)], ['query']),
  'getSoilReports' : IDL.Func([], [IDL.Vec(SoilReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FarmerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'respondToExpertQuery' : IDL.Func([QueryId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitExpertQuery' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [QueryId], []),
  'updateCropAdvisory' : IDL.Func(
      [AdvisoryId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGovernmentScheme' : IDL.Func(
      [SchemeId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMandiPrice' : IDL.Func([PriceId, IDL.Text, IDL.Int, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdvisoryId = IDL.Nat;
  const SchemeId = IDL.Nat;
  const PriceId = IDL.Nat;
  const SoilReportId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FarmerId = IDL.Nat;
  const FarmerProfile = IDL.Record({
    'id' : FarmerId,
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'landSize' : IDL.Float64,
    'location' : IDL.Text,
  });
  const CropAdvisory = IDL.Record({
    'id' : AdvisoryId,
    'crop' : IDL.Text,
    'season' : IDL.Text,
    'guidance' : IDL.Text,
  });
  const QueryId = IDL.Nat;
  const ExpertQuery = IDL.Record({
    'id' : QueryId,
    'farmerId' : FarmerId,
    'question' : IDL.Text,
    'owner' : IDL.Principal,
    'response' : IDL.Opt(IDL.Text),
    'attachment' : IDL.Opt(IDL.Text),
  });
  const GovernmentScheme = IDL.Record({
    'id' : SchemeId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
  });
  const MandiPrice = IDL.Record({
    'id' : PriceId,
    'crop' : IDL.Text,
    'price' : IDL.Int,
    'location' : IDL.Text,
  });
  const SoilReport = IDL.Record({
    'id' : SoilReportId,
    'ph' : IDL.Float64,
    'farmerId' : FarmerId,
    'owner' : IDL.Principal,
    'recommendations' : IDL.Text,
    'nutrients' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'landSize' : IDL.Float64,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCropAdvisory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AdvisoryId],
        [],
      ),
    'addGovernmentScheme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SchemeId],
        [],
      ),
    'addMandiPrice' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [PriceId], []),
    'addSoilReport' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [SoilReportId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCropAdvisory' : IDL.Func([AdvisoryId], [], []),
    'deleteGovernmentScheme' : IDL.Func([SchemeId], [], []),
    'deleteMandiPrice' : IDL.Func([PriceId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropAdvisories' : IDL.Func([], [IDL.Vec(CropAdvisory)], ['query']),
    'getCropAdvisory' : IDL.Func(
        [AdvisoryId],
        [IDL.Opt(CropAdvisory)],
        ['query'],
      ),
    'getExpertQueries' : IDL.Func([], [IDL.Vec(ExpertQuery)], ['query']),
    'getExpertQuery' : IDL.Func([QueryId], [IDL.Opt(ExpertQuery)], ['query']),
    'getGovernmentScheme' : IDL.Func(
        [SchemeId],
        [IDL.Opt(GovernmentScheme)],
        ['query'],
      ),
    'getGovernmentSchemes' : IDL.Func(
        [],
        [IDL.Vec(GovernmentScheme)],
        ['query'],
      ),
    'getMandiPrice' : IDL.Func([PriceId], [IDL.Opt(MandiPrice)], ['query']),
    'getMandiPrices' : IDL.Func([], [IDL.Vec(MandiPrice)], ['query']),
    'getMigrationResult' : IDL.Func([], [IDL.Bool], ['query']),
    'getSoilReport' : IDL.Func(
        [SoilReportId],
        [IDL.Opt(SoilReport)],
        ['query'],
      ),
    'getSoilReports' : IDL.Func([], [IDL.Vec(SoilReport)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FarmerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'respondToExpertQuery' : IDL.Func([QueryId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitExpertQuery' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [QueryId],
        [],
      ),
    'updateCropAdvisory' : IDL.Func(
        [AdvisoryId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGovernmentScheme' : IDL.Func(
        [SchemeId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMandiPrice' : IDL.Func(
        [PriceId, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };