/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdvisoryId = bigint;
export interface CropAdvisory {
  'id' : AdvisoryId,
  'crop' : string,
  'season' : string,
  'guidance' : string,
}
export interface ExpertQuery {
  'id' : QueryId,
  'farmerId' : FarmerId,
  'question' : string,
  'owner' : Principal,
  'response' : [] | [string],
  'attachment' : [] | [string],
}
export type FarmerId = bigint;
export interface FarmerProfile {
  'id' : FarmerId,
  'preferredLanguage' : string,
  'name' : string,
  'landSize' : number,
  'location' : string,
}
export interface GovernmentScheme {
  'id' : SchemeId,
  'name' : string,
  'description' : string,
  'eligibility' : string,
}
export interface MandiPrice {
  'id' : PriceId,
  'crop' : string,
  'price' : bigint,
  'location' : string,
}
export type PriceId = bigint;
export type QueryId = bigint;
export type SchemeId = bigint;
export interface SoilReport {
  'id' : SoilReportId,
  'ph' : number,
  'farmerId' : FarmerId,
  'owner' : Principal,
  'recommendations' : string,
  'nutrients' : string,
}
export type SoilReportId = bigint;
export interface UserProfile {
  'preferredLanguage' : string,
  'name' : string,
  'landSize' : number,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCropAdvisory' : ActorMethod<[string, string, string], AdvisoryId>,
  'addGovernmentScheme' : ActorMethod<[string, string, string], SchemeId>,
  'addMandiPrice' : ActorMethod<[string, bigint, string], PriceId>,
  'addSoilReport' : ActorMethod<[number, string, string], SoilReportId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCropAdvisory' : ActorMethod<[AdvisoryId], undefined>,
  'deleteGovernmentScheme' : ActorMethod<[SchemeId], undefined>,
  'deleteMandiPrice' : ActorMethod<[PriceId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCropAdvisories' : ActorMethod<[], Array<CropAdvisory>>,
  'getCropAdvisory' : ActorMethod<[AdvisoryId], [] | [CropAdvisory]>,
  'getExpertQueries' : ActorMethod<[], Array<ExpertQuery>>,
  'getExpertQuery' : ActorMethod<[QueryId], [] | [ExpertQuery]>,
  'getGovernmentScheme' : ActorMethod<[SchemeId], [] | [GovernmentScheme]>,
  'getGovernmentSchemes' : ActorMethod<[], Array<GovernmentScheme>>,
  'getMandiPrice' : ActorMethod<[PriceId], [] | [MandiPrice]>,
  'getMandiPrices' : ActorMethod<[], Array<MandiPrice>>,
  'getMigrationResult' : ActorMethod<[], boolean>,
  'getSoilReport' : ActorMethod<[SoilReportId], [] | [SoilReport]>,
  'getSoilReports' : ActorMethod<[], Array<SoilReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [FarmerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'respondToExpertQuery' : ActorMethod<[QueryId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitExpertQuery' : ActorMethod<[string, [] | [string]], QueryId>,
  'updateCropAdvisory' : ActorMethod<
    [AdvisoryId, string, string, string],
    undefined
  >,
  'updateGovernmentScheme' : ActorMethod<
    [SchemeId, string, string, string],
    undefined
  >,
  'updateMandiPrice' : ActorMethod<
    [PriceId, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];