/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GovernmentScheme {
    id: SchemeId;
    name: string;
    description: string;
    eligibility: string;
}
export type SoilReportId = bigint;
export interface SoilReport {
    id: SoilReportId;
    ph: number;
    farmerId: FarmerId;
    owner: Principal;
    recommendations: string;
    nutrients: string;
}
export interface CropAdvisory {
    id: AdvisoryId;
    crop: string;
    season: string;
    guidance: string;
}
export interface ExpertQuery {
    id: QueryId;
    farmerId: FarmerId;
    question: string;
    owner: Principal;
    response?: string;
    attachment?: string;
}
export type AdvisoryId = bigint;
export type FarmerId = bigint;
export interface FarmerProfile {
    id: FarmerId;
    preferredLanguage: string;
    name: string;
    landSize: number;
    location: string;
}
export type PriceId = bigint;
export type QueryId = bigint;
export type SchemeId = bigint;
export interface UserProfile {
    preferredLanguage: string;
    name: string;
    landSize: number;
    location: string;
}
export interface MandiPrice {
    id: PriceId;
    crop: string;
    price: bigint;
    location: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCropAdvisory(crop: string, guidance: string, season: string): Promise<AdvisoryId>;
    addGovernmentScheme(name: string, description: string, eligibility: string): Promise<SchemeId>;
    addMandiPrice(crop: string, price: bigint, location: string): Promise<PriceId>;
    addSoilReport(ph: number, nutrients: string, recommendations: string): Promise<SoilReportId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCropAdvisory(id: AdvisoryId): Promise<void>;
    deleteGovernmentScheme(id: SchemeId): Promise<void>;
    deleteMandiPrice(id: PriceId): Promise<void>;
    getCallerUserProfile(): Promise<FarmerProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCropAdvisories(): Promise<Array<CropAdvisory>>;
    getCropAdvisory(id: AdvisoryId): Promise<CropAdvisory | null>;
    getExpertQueries(): Promise<Array<ExpertQuery>>;
    getExpertQuery(id: QueryId): Promise<ExpertQuery | null>;
    getGovernmentScheme(id: SchemeId): Promise<GovernmentScheme | null>;
    getGovernmentSchemes(): Promise<Array<GovernmentScheme>>;
    getMandiPrice(id: PriceId): Promise<MandiPrice | null>;
    getMandiPrices(): Promise<Array<MandiPrice>>;
    getMigrationResult(): Promise<boolean>;
    getSoilReport(id: SoilReportId): Promise<SoilReport | null>;
    getSoilReports(): Promise<Array<SoilReport>>;
    getUserProfile(user: Principal): Promise<FarmerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    respondToExpertQuery(id: QueryId, response: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitExpertQuery(question: string, attachment: string | null): Promise<QueryId>;
    updateCropAdvisory(id: AdvisoryId, crop: string, guidance: string, season: string): Promise<void>;
    updateGovernmentScheme(id: SchemeId, name: string, description: string, eligibility: string): Promise<void>;
    updateMandiPrice(id: PriceId, crop: string, price: bigint, location: string): Promise<void>;
}
import type { CropAdvisory as _CropAdvisory, ExpertQuery as _ExpertQuery, FarmerId as _FarmerId, FarmerProfile as _FarmerProfile, GovernmentScheme as _GovernmentScheme, MandiPrice as _MandiPrice, QueryId as _QueryId, SoilReport as _SoilReport, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCropAdvisory(arg0: string, arg1: string, arg2: string): Promise<AdvisoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCropAdvisory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCropAdvisory(arg0, arg1, arg2);
            return result;
        }
    }
    async addGovernmentScheme(arg0: string, arg1: string, arg2: string): Promise<SchemeId> {
        if (this.processError) {
            try {
                const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGovernmentScheme(arg0, arg1, arg2);
            return result;
        }
    }
    async addMandiPrice(arg0: string, arg1: bigint, arg2: string): Promise<PriceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMandiPrice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMandiPrice(arg0, arg1, arg2);
            return result;
        }
    }
    async addSoilReport(arg0: number, arg1: string, arg2: string): Promise<SoilReportId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoilReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoilReport(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCropAdvisory(arg0: AdvisoryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCropAdvisory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCropAdvisory(arg0);
            return result;
        }
    }
    async deleteGovernmentScheme(arg0: SchemeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGovernmentScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGovernmentScheme(arg0);
            return result;
        }
    }
    async deleteMandiPrice(arg0: PriceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMandiPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMandiPrice(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<FarmerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropAdvisories(): Promise<Array<CropAdvisory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropAdvisories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropAdvisories();
            return result;
        }
    }
    async getCropAdvisory(arg0: AdvisoryId): Promise<CropAdvisory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropAdvisory(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropAdvisory(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpertQueries(): Promise<Array<ExpertQuery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpertQueries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpertQueries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpertQuery(arg0: QueryId): Promise<ExpertQuery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpertQuery(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpertQuery(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGovernmentScheme(arg0: SchemeId): Promise<GovernmentScheme | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGovernmentScheme(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGovernmentScheme(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGovernmentSchemes(): Promise<Array<GovernmentScheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGovernmentSchemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGovernmentSchemes();
            return result;
        }
    }
    async getMandiPrice(arg0: PriceId): Promise<MandiPrice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMandiPrice(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMandiPrice(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMandiPrices(): Promise<Array<MandiPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMandiPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMandiPrices();
            return result;
        }
    }
    async getMigrationResult(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMigrationResult();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMigrationResult();
            return result;
        }
    }
    async getSoilReport(arg0: SoilReportId): Promise<SoilReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoilReport(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoilReport(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoilReports(): Promise<Array<SoilReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoilReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoilReports();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<FarmerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async respondToExpertQuery(arg0: QueryId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToExpertQuery(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToExpertQuery(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitExpertQuery(arg0: string, arg1: string | null): Promise<QueryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExpertQuery(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExpertQuery(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCropAdvisory(arg0: AdvisoryId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCropAdvisory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCropAdvisory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGovernmentScheme(arg0: SchemeId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGovernmentScheme(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGovernmentScheme(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMandiPrice(arg0: PriceId, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMandiPrice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMandiPrice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ExpertQuery_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpertQuery): ExpertQuery {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpertQuery]): ExpertQuery | null {
    return value.length === 0 ? null : from_candid_ExpertQuery_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GovernmentScheme]): GovernmentScheme | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MandiPrice]): MandiPrice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoilReport]): SoilReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerProfile]): FarmerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropAdvisory]): CropAdvisory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QueryId;
    farmerId: _FarmerId;
    question: string;
    owner: Principal;
    response: [] | [string];
    attachment: [] | [string];
}): {
    id: QueryId;
    farmerId: FarmerId;
    question: string;
    owner: Principal;
    response?: string;
    attachment?: string;
} {
    return {
        id: value.id,
        farmerId: value.farmerId,
        question: value.question,
        owner: value.owner,
        response: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.response)),
        attachment: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.attachment))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpertQuery>): Array<ExpertQuery> {
    return value.map((x)=>from_candid_ExpertQuery_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
